import json, re

ARKADAS = [
    "lan bugün çok yoruldum ya ne kadar zor bir gün geçirdim",
    "moruk naber ne yapıyorsun bu akşam buluşalım mı",
    "kanka sana önemli bir şey söylemem lazım ciddi konuşalım",
    "abi bu hafta sonu plan var mı bir yerlere gidelim",
    "ya çok komik bir şey oldu bugün anlatsam inanmazsın",
    "ne yapıyorsun ya akşam serbest misin buluşalım",
    "moruk seni uzun zamandır göremedim çok özledim",
    "kanka bu gece ne yapıyorsun çıkalım mı dışarı",
    "abi nerede olduğunu hiç anlamıyorum ulaşamıyorum sana",
    "ya dün çok eğlenceli bir gün geçirdik tekrar yapalım",
    "lan sen hâlâ uyuyor musun kalk artık geç kalıyoruz",
    "moruk bugün bana yazabilirsin bir sorun yoksa ne zaman müsaitsin",
    "kanka iyi misin senden bir süredir haber alamıyorum",
    "abi yarın ne yapıyorsun beraber gidelim bir şeyler yapalım",
    "naber moruk çok zamandır görüşemedik hayat nasıl gidiyor",
    "kanka akşam müsait misin bir kafede oturalım konuşalım",
    "lan bu hafta sonu kesinlikle görüşelim tamam mı plan var",
    "abi telefonu açmıyorsun ne oldu sana ulaşmaya çalışıyorum",
    "ya seninle bir şey paylaşmak istiyorum çok önemli bir konu",
    "bu akşam ne yapıyoruz bir yere çıkalım mı dedim ya",
    "hadi sinemaya gidelim yeni film çıkmış çok iyi diyorlar",
    "akşam yemek yiyelim bir yer seçeyim mi yoksa sen mi seçersin",
    "konsere gitmek ister misin bilet aldım sana da alabilirim",
    "kanka şehir dışına çıkalım bu hafta sonu değişiklik yapalım",
    "abi buluşma saatini değiştirmek zorundayım özür dilerim",
    "ya nereye gidelim sen karar ver ben nereye dersen giderim",
    "lan bu akşam eve gel bir şeyler yapalım sıkıldım evde",
    "moruk cumartesi günü planın ne var boş musun o gün",
    "kanka alışverişe çıkıyorum sen de gel eğlenceli olur",
    "abi pazar sabahı kahvaltıya gidelim güzel bir yer biliyorum",
    "ya bu hafta sonu plajda olmak istiyorum sen de gelir misin",
    "hadi kafaya takma dışarı çıkalım biraz hava alalım iyidir",
    "moruk biraz dolaşmak istiyorum seninle çıkalım ne dersin",
    "kanka şu yeni kafede buluşalım çok güzelmiş gidin bakın",
    "abi akşam oyun oynayalım mı online da olur çağırırım seni",
    "ya geç kaldım özür dilerim hemen yola çıkıyorum az kaldı",
    "lan neredeysen gel zaten çok uzak değil sen de biliyorsun",
    "moruk seninle gezmek her zaman çok eğlenceli oluyor iyi ki varsın",
    "kanka bu ay çok harcama yaptım biraz ekonomik bir plan yapalım",
    "ya çok bunaldım son zamanlarda seninle konuşmak istedim",
    "abi sana bir şey anlatacağım ama kimseye söyleme tamam mı",
    "kanka çok kötü bir şey oldu bugün nasıl toparlarım bilemedim",
    "lan moruk çok üzgünüm ne yapacağımı bilmiyorum yardım et",
    "ya bu hafta her şey üst üste geldi dayanamayacak gibi oldum",
    "abi seninle konuşunca her zaman daha iyi hissediyorum teşekkürler",
    "kanka zor zamanlarımda hep yanımda oldun çok şükür",
    "moruk bugün çok sinirli bir gün geçirdim anlayış göster biraz",
    "ya kafam çok karışık şu an ne yapacağımı bilemedim gerçekten",
    "abi korktum bugün çok kötü bir şey olacaktı neyse ki olmadı",
    "kanka seninle geçirdiğimiz zamanlar çok güzeldi özledim onları",
    "lan bugün ağladım ya çok saçma bir şey ama gerçekten etkiledi",
    "moruk sen olmasaydın bu kadar kolay atlatamaz idim bu süreci",
    "ya insanlar bazen çok yoruyor anlıyor musun beni",
    "abi kafaya çok taktım bu konuyu artık bırakmam lazım sanırım",
    "kanka bir şeye çok sinirleniyorum ama söylersem anlar mısın",
    "moruk bazen hayat çok bunaltıcı geliyor yanımda ol sadece",
    "ya bu hafta çok iyi şeyler de oldu sana anlatmak istiyorum",
    "abi çok yoruldum ama seninle konuşunca geçiyor yorgunluk",
    "kanka teşekkür ederim hep yanımda olduğun için gerçekten",
    "ya bugün çok saçma bir şey yaptım utanacak gibi oldum",
    "lan inanmayacaksın bugün ne oldu anlatayım güleceksin",
    "moruk sen de böyle aptalca bir şey yaptın mı hiç hayatında",
    "kanka bu kadar gülünç bir şey olmaz ya nasıl oldu buna",
    "abi şu videoyu gönderiyorum izle hayatımda böyle bir şey görmedim",
    "ya ne kadar komik bir adam var çevremde anlayamazsın",
    "lan bu memeyi gördün mü tam senlik bir şey paylaştım",
    "moruk oğlum sen çok absürd bir insansın ya gerçekten",
    "kanka bu olayı okuyunca çok güldüm gözyaşlarım aktı",
    "abi bence sen çok eğlenceli bir insansın seninle olmak güzel",
    "ya şu arkadaşımız ne yaptı biliyor musun iyice çıldırdı",
    "lan bugün çok komik bir film izledim seninle izleseydik",
    "moruk benden daha aptal karar veren biri varsa oyum ona",
    "kanka sana bir şey soracağım ama gülersin belki söyleyeyim mi",
    "abi oğlum sen bazen çok saçma şeyler söylüyorsun ama seviyorum",
    "ya kafayı yedim artık çalışmaktan ders çalışmaktan bittim",
    "lan o kadarcık şeye bu kadar üzülmek neden bilmiyorum",
    "moruk bugün öyle bir şey gördüm ki gözlerime inanamadım",
    "kanka en son ne zaman bu kadar güldüğünü hatırlıyor musun",
    "abi gülmekten karın ağrısı olacak anlattığında göreceksin",
    "ya bugün derste hiçbir şey anlamadım sen anladın mı",
    "abi ödev için bir araya gelip çalışalım mı yarın müsait misin",
    "kanka sınav yaklaşıyor hiç çalışmadım ya panikladım şimdi",
    "moruk notlarını paylaşır mısın hiç yazmadım derste bugün",
    "lan bu ders çok zor değil mi anlamak için çok uğraşıyorum",
    "ya finalden korktum çok şey var kapsama alınmış olan",
    "abi grup ödevimiz var beraber çalışalım mı bu hafta",
    "kanka hoca bu sınavı çok zor yapmış geçen sene bakıyorum",
    "moruk derse girmeden kayıtları dinleyebilirim diye düşünüyorum",
    "lan bugün kampüste vakit geçirelim birlikte çalışabiliriz",
    "ya bu dersi seven biri var mı sınıfta ben hiç sevmiyorum",
    "abi bana biraz anlat şunu anlamadım bir yerde takıldım",
    "kanka sabah erkenden giriyor artık hoca hiç iyi değil bu",
    "moruk benim için biraz yer tut derse geç kalacağım bugün",
    "lan canım sıkılıyor derse girmek istemiyorum bugün gel kaç",
    "ya sınıfta kalmak istemiyorum artık dışarı çıkalım biraz",
    "abi bitirme projesini ne zaman yapacaksın yardım edebilirim",
    "kanka bölümden nefret ediyorum ama seni seviyorum neyse",
    "moruk mezun olunca ne yapacaksın bir fikrin var mı şu an",
    "lan bu hoca çok sıkıcı anlatıyor uyuya yazıyorum öyle",
    "ya bugün ne yesek bir türlü karar veremedim açım ayrıca",
    "abi pizza ısmarlayalım mı bu gece evde oturup izleriz",
    "kanka o yerden döner yiyelim mi çok özledim orayı",
    "moruk sabahtan beri hiçbir şey yemedim çok acıktım şimdi",
    "lan akşam yemek yapacak vaktim yok birlikte gidelim dışarı",
    "ya kafeye gidelim mi biraz oturalım konuşalım güzel olur",
    "abi çay içmek istiyorum eve gel birlikte oturalım konuşalım",
    "kanka şu yeni restorana gitmedim hâlâ iyi midir gerçekten",
    "moruk paket servis mı yaptıralım eve yoksa dışarı mı çıkalım",
    "lan yemek pişirmek istemiyorum bugün dışarı çıkalım hadi",
    "ya hamburger istiyorum çok zamandır yemedim senden yardım",
    "abi o yerde çok iyi bir şey yedik hatırlıyor musun tekrar",
    "kanka sabah kahvaltısı yapalım birlikte pazar günü olur mu",
    "moruk akşam yemek için bir araya gelelim ne dersin",
    "lan abur cubur yiyorum sürekli sağlıklı bir şeyler yiyelim",
    "ya bu oyunu indirdim çok bağımlılık yapıyor dikkat et",
    "abi sosyal medyayı bırakmak istiyorum ama yapamıyorum ki",
    "kanka şu videoyu izle çok güzel bir şey keşfettim bugün",
    "moruk telefonum çok yavaşladı yenisini almam lazım artık",
    "lan bu uygulamayı kullanıyor musun çok işe yarıyor bana",
    "ya internet çekmiyor evde çok sinir bozucu bu durum",
    "abi şu dizi çıktı izlemedim sen izledin mi ne kadar güzel",
    "kanka podcast öneri ver uzun yolculuğum var yarın gideceğim",
    "moruk telefon kırıldı felakete uğradım ne yapacağımı bilmiyorum",
    "lan o oyunun yeni güncellemesi geldi çok iyi şeyler eklemişler",
    "ya hayat bazen çok güzel bazen çok zorlu anlamak güç",
    "abi gelecekte ne olmak istiyorsun hiç düşündün mü bunu",
    "kanka bu şehirde yaşamaktan bazen bunalıyorum ama hâlâ iyiyiz",
    "moruk en mutlu olduğun an hangisiydi düşündün mü hiç",
    "lan seninle geçen her an güzel oluyor gerçekten teşekkürler",
    "ya arkadaşlık çok değerli bir şey iyi ki seninle tanıştım",
    "abi bazen insanlara güvenmek çok zor geliyor biliyor musun",
    "kanka sana söyleyeceğim bir şey var ama nasıl söyleyeceğimi bilmiyorum",
    "moruk şu an çok iyi hissediyorum seninle konuşunca geçti",
    "lan her şey yolunda gidecek merak etme her zaman iyiye gider",
    "naber",
    "ne yapıyorsun",
    "müsait misin",
    "hadi gel",
    "tamam görüşürüz",
    "arayacağım seni",
    "mesaj at bana",
    "evet gelebilirim",
    "hayır bugün olmaz",
    "biraz sonra yazarım",
    "yolda geliyorum",
    "geç kaldım özür",
    "neredeysin şu an",
    "çok güldüm ya",
    "harika olmuş bu",
    "çok saçma bu ya",
    "anlamadım bunu açıkla",
    "kesinlikle katılıyorum",
    "bence de öyle",
    "hmm düşüneyim biraz",
    "yarın konuşalım olur mu",
    "seni özledim ya gerçekten",
    "hayatımdasın iyi ki",
    "sen en iyisisin moruk",
    "teşekkürler her şey için",
    "güle güle görüşürüz",
    "hayırlı olsun umarım",
    "geçmiş olsun umarım iyi olur",
    "tebrikler çok mutlu oldum",
    "üzüldüm çok kötü olmuş",
]

HOCA = [
    "Hocam iyi günler size ulaşmak istedim bir konuda yardımınıza ihtiyacım var",
    "Sayın hocam ödev hakkında bir sorum olacaktı uygun olduğunuzda cevaplayabilir misiniz",
    "Hocam sınav tarihi hakkında bilgi alabilir miyim hangi konulardan sorumlu olduğumu öğrenmek istiyorum",
    "Hocam randevu almak istiyorum müsait olduğunuz bir zaman dilimi var mı",
    "Hocam proje teslim tarihi hakkında bilgi almak istedim son gün ne zamandı",
    "Sayın hocam iyi akşamlar size bir konuyu danışmak istiyorum müsait misiniz",
    "Hocam iyi çalışmalar dilerim bir sorum olacaktı uygun bir vakit ayırabilir misiniz",
    "Hocam saygılarımla arz ederim bir konuda görüşünüze ihtiyaç duyuyorum",
    "Sayın hocam iyi günler dersinizle ilgili bir şeyi merak ediyorum sorabilir miyim",
    "Hocam size ulaşmak istedim çünkü önemli bir konuyu paylaşmam gerekiyor",
    "Hocam iyi sabahlar bugün ders saat kaçta başlıyor öğrenmek istedim",
    "Sayın hocam geç kaldığım için özür dilerim ders devam ediyor mu hâlâ",
    "Hocam bilgilerinize sunmak istiyorum bir konuyu değerlendirmenizi rica ediyorum",
    "Sayın hocam merhaba yardımınıza ihtiyacım var bu konuda ne yapmalıyım",
    "Hocam rahatsız ettiğim için özür dilerim ancak önemli bir konuyu sormam gerekiyordu",
    "Hocam ödev konusu hakkında ek bilgi alabilir miyim tam olarak ne isteniyor",
    "Sayın hocam proje gereksinimlerini anlamakta güçlük çekiyorum açıklar mısınız",
    "Hocam bitirme projem hakkında görüşmek istiyorum ne zaman müsaitsiniz",
    "Hocam grup ödevinde görev dağılımı nasıl yapılmalı yönlendirmenizi bekliyorum",
    "Sayın hocam projenin teknik kısmında takıldım yardımınızı rica ediyorum",
    "Hocam teslim formatı hakkında bilgi alabilir miyim PDF mi Word mu olmalı",
    "Hocam ödev kaynakları için öneri alabilir miyim hangi kaynakları kullanmalıyım",
    "Sayın hocam proje sunumunu ne zaman yapacağız tarih belirlendi mi",
    "Hocam ödevimi gönderdim ama onay alamadım ulaştı mı kontrol edebilir misiniz",
    "Hocam proje sürecinde ne tür hatalar yapmamalıyım önerinizi almak istiyorum",
    "Sayın hocam araştırma metodolojisi konusunda rehberlik almanız için yazıyorum",
    "Hocam literatür taraması için hangi veri tabanlarını kullanmamı önerirsiniz",
    "Sayın hocam tez konumu netleştirmek için görüşmenizi talep ediyorum",
    "Hocam proje raporumda eksik olan kısımlar var mı değerlendirmenizi bekliyorum",
    "Sayın hocam verilen geri bildirimler doğrultusunda revizyonu tamamladım",
    "Hocam sınav kapsamı hakkında bilgi alabilir miyim hangi konular dahil",
    "Sayın hocam vize notum sisteme girmemiş kontrol edebilir misiniz",
    "Hocam final sınavı için ek kaynak önerir misiniz çalışmak istiyorum",
    "Sayın hocam sınav sonuçları ne zaman açıklanacak merak ediyorum",
    "Hocam itiraz hakkım var mı notumla ilgili bir sorum olacaktı",
    "Sayın hocam sınav kağıdımı görmek istiyorum mümkün müdür bu",
    "Hocam geçer not alamadım tekrar sınav hakkım var mı öğrenmek istedim",
    "Sayın hocam ek sınav başvurusu için ne yapmalıyım süreci anlatır mısınız",
    "Hocam bu dönem devamsızlık limitini aştım ne yapmalıyım durumum ne",
    "Sayın hocam telafi sınavına girmek istiyorum başvuru nasıl yapılıyor",
    "Hocam ödev puanım eksik görünüyor sistemi kontrol eder misiniz lütfen",
    "Sayın hocam dönem notu hesaplamaya dahil edilecek kriterler nelerdir",
    "Hocam başarılı sayılmak için minimum kaç puan almam gerekiyor",
    "Sayın hocam bütünleme sınavına girebilmek için koşullar nelerdir",
    "Hocam transkriptimde hata var nasıl düzeltebilirim bunu öğrenmek istedim",
    "Hocam bugün derse gelemeyeceğim sağlık sorunum var mazeret belgesi sunabilirim",
    "Sayın hocam geçen hafta derse katılamadım önemli bir sebep vardı özür dilerim",
    "Hocam devamsızlık durumumu öğrenmek istiyorum kaç gün kaldım şu an",
    "Sayın hocam hastanede rapor aldım mazeretime kabul eder misiniz",
    "Hocam ailevi bir sorun yaşadım bu hafta derse katılamayacağım anlayışınıza sığınıyorum",
    "Sayın hocam mazeret sınavına girebilmek için ne yapmalıyım süreci öğrenmek istiyorum",
    "Hocam dersi kaçırdım ders notu paylaşılıyor mu elde edebilir miyim",
    "Sayın hocam bugün toplantıya katılmam gerekiyor dersi kaçırmak zorunda kalacağım",
    "Hocam bursiyerim ve zorunlu bir etkinlikteyim derse katılamayacağım durumum nedir",
    "Sayın hocam kaçırdığım dersin içeriğini nasıl telafi edebilirim yönlendirmenizi istiyorum",
    "Hocam referans mektubu yazmanızı rica etmek istiyorum değerlendirir misiniz",
    "Sayın hocam yüksek lisans başvurusu için tavsiye mektubuna ihtiyacım var",
    "Hocam kariyerim hakkında görüşünüzü almak istiyorum müsait bir zaman var mı",
    "Sayın hocam akademik yolda devam etmek istiyorum önerinizi bekliyorum",
    "Hocam staj için referans olabilir misiniz şirkete başvuracağım yakında",
    "Sayın hocam doktora başvurusu için hazırlık sürecinde yardım alabilir miyim",
    "Hocam araştırma asistanı pozisyonu için başvurmak istiyorum uygun müyüm",
    "Sayın hocam iş hayatına geçiş için önerilerinizi almak istiyorum değerli görüşleriniz",
    "Hocam projemin makale olarak yayımlanması için ne yapmalıyım süreç nedir",
    "Sayın hocam akademik çalışmamı geliştirmek için mentorlük alabilir miyim",
    "Hocam bu konuyu anlamakta güçlük çekiyorum ek kaynak önerir misiniz",
    "Sayın hocam derste geçen kavramı tam anlamadım açıklar mısınız biraz daha",
    "Hocam ödevi yaparken takıldım bir kısım var yardımınızı rica ediyorum",
    "Sayın hocam metodoloji bölümünü nasıl yazmalıyım örnek gösterebilir misiniz",
    "Hocam araştırma sorusunu nasıl daraltabilirim çok geniş kaldı bence",
    "Sayın hocam veri analizi için hangi yazılımı kullanmamı önerirsiniz",
    "Hocam istatistiksel yöntemler konusunda kaynak önerir misiniz çalışıyorum",
    "Sayın hocam bulgularımı yorumlamakta güçlük çekiyorum rehberlik edebilir misiniz",
    "Hocam proje takvimini nasıl yönetmem gerekiyor önerinizi almak istiyorum",
    "Sayın hocam akademik yazım kuralları konusunda eksiklerim var nasıl gelişebilirim",
    "Hocam ilginiz için çok teşekkür ederim çok yardımcı oldunuz gerçekten",
    "Sayın hocam değerli zamanınızı ayırdığınız için minnettarım saygılarımla",
    "Hocam desteğiniz için teşekkür ederim başarılarımda büyük payınız var",
    "Sayın hocam geri bildiriminiz için çok teşekkür ederim faydalı oldu",
    "Hocam anlayışınız için teşekkür ederim saygılarımla iyi çasüreç nasıl işliyor anlatır mısınız",
    "Hocam imzanıza ihtiyacım var staj belgesi için müsait misiniz bugün",
    "Sayın hocam dilekçemi imzalamanızı rica ediyorum gereği için arz ederim",
    "Hocam ders kaydı konusunda yardıma ihtiyacım var sistemi anlayamadım",
    "Sayın hocam seçmeli ders seçiminde önerinizi almak istiyorum ne uygun olur",
    "Hocam öğrenci belgesi için imzanıza ihtiyacım var ne zaman müsaitsiniz",
    "Sayın hocam ders değişikliği yapmak istiyorum mümkün mü bu dönem için",
    "Hocam çift anadal başvurusu hakkında bilgi alabilir miyim koşullar nedir",
    "Sayın hocam yandal programına kaydolmak istiyorum ne yapmalıyım başlangıç için",
    "Hocam burs başvurusu için referans formu doldurmanızı rica ediyorum",
    "Hocam iyi günler",
    "Sayın hocam iyi akşamlar",
    "Hocam teşekkür ederim",
    "Saygılarımla sunarım",
    "Bilgilerinize arz ederim",
    "İyi çalışmalar dilerim",
    "Hocam anlayışınız için teşekkürler",
    "Cevabınızı bekliyorum saygıyla",
    "Hocam müsait misiniz görüşmek için",
    "Sayın hocam geri dönüşünüzü bekliyorum",
    "Hocam randevumuzu onaylıyor musunuz",
    "Saygılarımla iyi günler dilerim",
    "Hocam durumu değerlendirmenizi rica ederim",
    "Sayın hocam yardımlarınız için minnettarım",
    "Hocam en kısa sürede dönmenizi rica ederim",
    "Saygı ve sevgilerimle iyi günler",
    "Hocam konuyu netleştirmek için yazıyorum",
    "Sayın hocam önerinizi bekliyorum teşekkürler",
    "Hocam durumumu değerlendirmenizi istiyorum",
    "Saygılarımla arz ederim hocam iyi günler",
]

output_path = "/Users/senases/Desktop/context-aware-turkish-keyboard/data/context_data.json"

with open(output_path, "r", encoding="utf-8") as f:
    data = json.load(f)

print("Önce:")
for k, v in data.items():
    print(f"  {k}: {len(v)} cümle")

data["arkadas"] = ARKADAS
data["hoca"] = HOCA

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("\nSonra:")
for k, v in data.items():
    print(f"  {k}: {len(v)} cümle")
print("\nTamam!")
